### ISSUE TITLE
missing daw_consteval.h ? 

### ISSUE THREAD

**Issue by cbelous** [beached/daw_json_link#451]
Hello, 

Is that possible header file daw_consteval.h is missing from master ? 

I am getting that error on compile in version 3.28.3: 
daw_json_link-3.28.3\include\daw\json\daw_json_switches.h(14,10): error C1083: Cannot open include file: 'daw/daw_consteval.h'

Thank you, 
Constantine

**Comment by beached** [comment]
Seems like you only pulled in the 1 repo and are not using cmake/vcpkg or conan.  You will need to pull in https://github.com/beached/header_libraries.git and https://github.com/beached/utf_range.git too.  Or use vcpkg or conan,  or cmake(which will use FetchContent to pull them in)

**Comment by cbelous** [comment]
Hey, thanks for quick reply and for that library, it's very useful .
May be you can update the readme page, as the dependency on two other repos is not obvious. 
When I see header-only library I expect single header folder and ready to go, that appears there is more in play here. 
Thanks!
